-- Create todos table
create table public.todos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  task text not null,
  is_completed boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.todos enable row level security;

-- Create policy to allow users to only see their own todos
create policy "Users can view their own todos"
  on public.todos for select
  using ( auth.uid() = user_id );

-- Create policy to allow users to insert their own todos
create policy "Users can insert their own todos"
  on public.todos for insert
  with check ( auth.uid() = user_id );

-- Create policy to allow users to update their own todos
create policy "Users can update their own todos"
  on public.todos for update
  using ( auth.uid() = user_id );

-- Create policy to allow users to delete their own todos
create policy "Users can delete their own todos"
  on public.todos for delete
  using ( auth.uid() = user_id );
